routes/web.php
<?php

use App\Http\Controllers\ContactController;
use Aimeos\Shop\Controller\CatalogController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Front Routes
Route::get('/', 'AccueilController@index');
Route::get('/home', 'AccueilController@home');
Route::get('/nosvins', 'NosVinsController@vins');
Route::get('/nosjus', 'NosJusController@jus');
Route::get('/commander', 'CommanderController@index');
Route::get('/galerie', 'GalerieController@galerie');


// Admin  Routes
Route::get('/admin', 'AdminController@index')->name('admin');


Auth::routes();


//Crud Routes
Route::resource('wines', 'NosVinsController')->middleware('admin');
Route::resource('juses', 'NosJusController')->middleware('admin');
Route::resource('galeries', 'GalerieController')->middleware('admin');


//Contact Routes

Route::get('contact', 'ContactController@create');
Route::post('contact', 'ContactController@store');

//Description wines/jus routes
Route::get('description/{id}', 'NosVinsController@show');
Route::get('descriptions/{id}', 'NosJusController@show');

//Route resource
Route::get('/galerie/description', 'GalerieResourceController@index');
Route::get('/wine/resource', 'WineRessourceController@index');
Route::get('/jus/resource', 'JusRessourceController@index');


//route commander
Route::get('/commander/addwine/{id}', 'CommanderController@addwine');
Route::get('/commander/basket', 'CommanderController@getitems');
Route::get('/commander/addjus/{id}', 'CommanderController@addjus');
Route::get('/commander/delete/{id}', 'CommanderController@deleteitem');
Route::get('/commander/basket/current', 'CommanderController@deleteitem');

//test
Route::get('/horizontal', "HorizontalController@index");

resources/views/juses/create.blade.php
@extends('layouts.main')
@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
       <h1 class="display-3">Ajouter un jus</h1>
       <div>
            <a href='{{ route('juses.index')}}' class="btn btn-primary">Retour a la liste des jus</a>
        </div>
     <div>
            @if ($errors->any())
            <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                  @endforeach
              </ul>
            </div><br />
          @endif
         <form method="post" action="{{ route ('juses.store') }}">
             @csrf
             <div class="form-group">
                 <label for="name">Nom:</label>
                 <input type="text" class="form-control" name="name"/>
             </div>

             <div class="form-group">
                 <label for="description">Cépage:</label>
                 <input type="text" class="form-control" name="description"/>
             </div>

             <div class="form-group">
                 <label for="degre">Degres:</label>
                 <input type="text" class="form-control" name="degre"/>
             </div>

             <div class="form-group">
                 <label for="vinification">vinification:</label>
                 <input type="text" class="form-control" name="vinification"/>
             </div>

             <div class="form-group">
                 <label for="prix">Prix</label>
                 <input type="text" class="form-control" name="prix"/>
             </div>

             <div class="form-group">
                <label for="image_irl">Photo:</label>
                <input type="text" class="form-control" name="image_url"/>
             </div>

             <button type="submit" class="btn btn-primary">Ajouter un jus</button>
         </form>

     </div>
     <div class="col-sm-12">

            @if(session()->get('success'))
              <div class="alert alert-success">
                {{ session()->get('success') }}
              </div>
            @endif
          </div>
   </div>
   </div>
@endsection

resources/views/juses/edit.blade.php
@extends('layouts.main')
@section('content')
<div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h1 class="display-3">Modifier un jus</h1>
            <div>
                <a href='{{ route('juses.index')}}' class="btn btn-primary">Retour</a>
            </div>

            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            <br />
            @endif
            <form method="post" action="{{ route('juses.update',["jus"=>$jus->id])}}">
                @method('PATCH')
                @csrf
                <div class="form-group">

                    <label for="name">Nom:</label>
                    <input type="text" class="form-control" name="name" value={{ $jus->name }} />
                </div>

                <div class="form-group">
                    <label for="description">Cépage:</label>
                    <input type="text" class="form-control" name="description" value={{ $jus->description }} />
                </div>

                <div class="form-group">
                    <label for="degres">Degres:</label>
                    <input type="text" class="form-control" name="degres" value={{ $jus->degres }} />
                </div>

                <div class="form-group">
                    <label for="vinification">Vinification:</label>
                    <input type="text" class="form-control" name="vinification" value={{$jus->vinification }} />
                </div>

                <div class="form-group">
                    <label for="prix">Prix:</label>
                    <input type="text" class="form-control" name="prix" value={{ $jus->prix }} />
                </div>

                <div class="form-group">
                    <label for="image_url">Photo:</label>
                    <input type="text" class="form-control" name="image_url" value={{$jus->image_url }} />
                </div>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
@endsection

resources/views/juses/index.blade.php
@extends('layouts.main')
@section('content')
{{-- changer le css --}}
<div class="allcontent">

        <div class="col-sm-5">
            <h1 class="display-3">Jus</h1>
            <div>
                <a href="{{ route('juses.create')}}" class="btn btn-primary">Nouveau Jus</a>
            </div>
            <div>
                <a href='{{ route('admin')}}' class="btn btn-primary">Retour à la page d'aministration</a>
            </div>
        </div>

        <div class="allwine">

                @foreach($juses as $jus)

                <div class="wine_img">
                    <div class="card">

                        <div class="wineimg">

                            <img class="card-img-top" src="{{$jus->image_url}}" alt="Card image cap">
                        </div>

                        <div class="card-body">

                            <h5 class="card-title">Nom</h5>
                            <p class="card-text">{{$jus->name}}</p>

                            <a href="{{ route('juses.edit',["jus"=>$jus->id])}}" class="btn btn-primary">Modifier</a>

                            <form action="{{ route('juses.destroy',["jus"=>$jus->id])}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger send" type="submit">Supprimer</button>
                                </form>

                        </div>
                    </div>
                </div>
                @endforeach
        </div>

            <div class="col-sm-12">

                @if(session()->get('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
                @endif
            </div>

</div>


@endsection