routes/web.php
<?php

use App\Http\Controllers\ContactController;
use Aimeos\Shop\Controller\CatalogController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Front Routes
Route::get('/', 'AccueilController@index');
Route::get('/home', 'AccueilController@home');
Route::get('/nosvins', 'NosVinsController@vins');
Route::get('/nosjus', 'NosJusController@jus');
Route::get('/commander', 'CommanderController@index');
Route::get('/galerie', 'GalerieController@galerie');


// Admin  Routes
Route::get('/admin', 'AdminController@index')->name('admin');


Auth::routes();


//Crud Routes
Route::resource('wines', 'NosVinsController')->middleware('admin');
Route::resource('juses', 'NosJusController')->middleware('admin');
Route::resource('galeries', 'GalerieController')->middleware('admin');


//Contact Routes

Route::get('contact', 'ContactController@create');
Route::post('contact', 'ContactController@store');

//Description wines/jus routes
Route::get('description/{id}', 'NosVinsController@show');
Route::get('descriptions/{id}', 'NosJusController@show');

//Route resource
Route::get('/galerie/description', 'GalerieResourceController@index');
Route::get('/wine/resource', 'WineRessourceController@index');
Route::get('/jus/resource', 'JusRessourceController@index');


//route commander
Route::get('/commander/addwine/{id}', 'CommanderController@addwine');
Route::get('/commander/basket', 'CommanderController@getitems');
Route::get('/commander/addjus/{id}', 'CommanderController@addjus');
Route::get('/commander/delete/{id}', 'CommanderController@deleteitem');
Route::get('/commander/basket/current', 'CommanderController@deleteitem');

//test
Route::get('/horizontal', "HorizontalController@index");

app/Wine.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;
use DivineOmega\LaravelExtendableBasket\Interfaces\Basketable;

class Wine extends Model implements Basketable
{
    protected $fillable = [
        "id",
        "nom",
        "description",
        "prix",
        "degres",
        "notes_degustation",
        "terroir",
        "vinification",
        "accord",
        "image_url",
    ];
    protected $table = "wines";

    public function getPrice()
    {
        return $this->prix;
    }
    public function getName()
    {
        return $this->nom;
    }
    public function deleteitem()
    {
        $item = $this->items->first();
        $item->delete();
    }
    // For resolve the error (laravel unknow column 'updated_at')
    public $timestamps = false;
}

resources/views/wines/create.blade.php
@extends('layouts.main')
@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
       <h1 class="display-3">Ajouter un vin</h1>
       <div>
            <a href='{{ route('wines.index')}}' class="btn btn-primary">Retour</a>
        </div>
     <div>
            @if ($errors->any())
            <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                  @endforeach
              </ul>
            </div><br />
          @endif
         <form method="post" action="{{ route ('wines.store') }}">
             @csrf
             <div class="form-group">
                 <label for="nom">Nom:</label>
                 <input type="text" class="form-control" name="nom"/>
             </div>

             <div class="form-group">
                 <label for="description">Cépage:</label>
                 <input type="text" class="form-control" name="description"/>
             </div>

             <div class="form-group">
                 <label for="prix">Prix</label>
                 <input type="text" class="form-control" name="prix"/>
             </div>

             <div class="form-group">
                 <label for="degres">Degres:</label>
                 <input type="text" class="form-control" name="degres"/>
             </div>
             <div class="form-group">
                 <label for="notes_degustation">Note de dégustation:</label>
                 <input type="text" class="form-control" name="notes_degustation"/>
             </div>

             <div class="form-group">
                <label for="terroir">Terroir:</label>
                <input type="text" class="form-control" name="terroir"/>
            </div>

            <div class="form-group">
                <label for="vinification">vinification:</label>
                <input type="text" class="form-control" name="vinification"/>
            </div>

            <div class="form-group">
                <label for="accord">Accord:</label>
                <input type="text" class="form-control" name="accord"/>
            </div>

            <div class="form-group">
                <label for="image_url">Photo:</label>
                <input type="text" class="form-control" name="image_url"/>
            </div>

             <button type="submit" class="btn btn-primary">Ajouter un vin</button>
         </form>

     </div>
     <div class="col-sm-12">

            @if(session()->get('success'))
              <div class="alert alert-success">
                {{ session()->get('success') }}
              </div>
            @endif
     </div>

   </div>
   </div>
@endsection

resources/views/wines/edit.blade.php
@extends('layouts.main')
@section('content')
<div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h1 class="display-3">Modifier un vin</h1>
            <div>
                    <a href='{{ route('wines.index')}}' class="btn btn-primary">Retour</a>
                </div>

            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            <br />
            @endif
            <form method="post" action="{{ route('wines.update',['wine'=> $wine->id])}}" >
                @method('PATCH')
                @csrf
                <div class="form-group">

                    <label for="nom">Nom:</label>
                    <input type="text" class="form-control" name="nom" value="{{ $wine->nom }}{{ old('nom') }}" />
                </div>

                <div class="form-group">
                    <label for="description">Cépage:</label>
                    <input type="text" class="form-control" name="description" value="{{ $wine->description }}{{ old('description') }}" />
                </div>

                <div class="form-group">
                    <label for="prix">Prix:</label>
                    <input type="text" class="form-control" name="prix" value="{{ $wine->prix }}{{ old('prix') }}"/>
                </div>
                <div class="form-group">
                    <label for="degres">Degres:</label>
                    <input type="text" class="form-control" name="degres" value="{{ $wine->degres }}{{ old('degres') }} "/>
                </div>
                <div class="form-group">
                    <label for="notes_degustation">notes de dégustation:</label>
                    <input type="text" class="form-control" name="notes_degustation" value="{{ $wine->notes_degustation }}{{ old('notes_degustation') }}"/>
                </div>
                <div class="form-group">
                    <label for="terroir"> Terroir:</label>
                    <input type="text" class="form-control" name="terroir"  value="{{$wine->terroir }}{{ old('terroir') }}"/>
                </div>

                <div class="form-group">
                    <label for="vinification">Vinification:</label>
                    <input type="text" class="form-control" name="vinification" value="{{$wine->vinification }}{{ old('vinification') }}"/>
                </div>

                <div class="form-group">
                    <label for="accord">Accord:</label>
                    <input type="text" class="form-control" name="accord" value="{{$wine->accord }}{{ old('accord') }}" />
                </div>

                <div class="form-group">
                    <label for="image_url">Image:</label>
                    <input class="form-control" name="image_url" value="{{$wine->image_url }}{{ old('image_url') }}"/>
                </div>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
@endsection

resources/views/wines/index.blade.php
@extends('layouts.main')
@section('content')

<div class="allcontent">

        <div class="col-sm-5">
            <h1 class="display-3">Vins</h1>
            <div>
                <a href="{{ route('wines.create')}}" class="btn btn-primary">Nouveau vin</a>
            </div>
            <div>
                <a href='{{ route('admin')}}' class="btn btn-primary">Retour à la page d'aministration</a>
            </div>
        </div>

        <div class="allwine">

                @foreach($wines as $wine)

                <div class="wine_img">
                    <div class="card">

                        <div class="wineimg">
                        <img type="file" class="card-img-top" src="{{$wine->image_url}}" alt="">
                            {{-- <img class="card-img-top" src="{{$wine->image_url}}" alt="Card image cap"> --}}
                        </div>

                        <div class="card-body">

                            <h5 class="card-title">Nom</h5>
                            <p class="card-text">{{$wine->nom}}</p>

                            <a href="{{ route('wines.edit',["wine"=>$wine->id])}}" class="btn btn-primary">Modifier</a>

                            <form action="{{ route('wines.destroy',["wine"=>$wine->id])}}" method="post" enctype="multipart/form-data">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger send" type="submit">Supprimer</button>
                                </form>

                        </div>
                    </div>
                </div>
                @endforeach
        </div>

            <div class="col-sm-12">

                @if(session()->get('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
                @endif
            </div>

</div>


@endsection