routes/web.php
<?php

use App\Http\Controllers\ContactController;
use Aimeos\Shop\Controller\CatalogController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Front Routes
Route::get('/', 'AccueilController@index');
Route::get('/home', 'AccueilController@home');
Route::get('/nosvins', 'NosVinsController@vins');
Route::get('/nosjus', 'NosJusController@jus');
Route::get('/commander', 'CommanderController@index');
Route::get('/galerie', 'GalerieController@galerie');


// Admin  Routes
Route::get('/admin', 'AdminController@index')->name('admin');


Auth::routes();


//Crud Routes
Route::resource('wines', 'NosVinsController')->middleware('admin');
Route::resource('juses', 'NosJusController')->middleware('admin');
Route::resource('galeries', 'GalerieController')->middleware('admin');


//Contact Routes

Route::get('contact', 'ContactController@create');
Route::post('contact', 'ContactController@store');

//Description wines/jus routes
Route::get('description/{id}', 'NosVinsController@show');
Route::get('descriptions/{id}', 'NosJusController@show');

//Route resource
Route::get('/galerie/description', 'GalerieResourceController@index');
Route::get('/wine/resource', 'WineRessourceController@index');
Route::get('/jus/resource', 'JusRessourceController@index');


//route commander
Route::get('/commander/addwine/{id}', 'CommanderController@addwine');
Route::get('/commander/basket', 'CommanderController@getitems');
Route::get('/commander/addjus/{id}', 'CommanderController@addjus');
Route::get('/commander/delete/{id}', 'CommanderController@deleteitem');
Route::get('/commander/basket/current', 'CommanderController@deleteitem');

//test
Route::get('/horizontal', "HorizontalController@index");

resources/views/galeries/create.blade.php
@extends('layouts.main')
@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
       <h1 class="display-3">Ajouter une photo</h1>
       <div>
            <a href='{{ route('galeries.index')}}' class="btn btn-primary">Retour a la liste des photos</a>
        </div>
     <div>
            @if ($errors->any())
            <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                  @endforeach
              </ul>
            </div><br />
          @endif
         <form method="post" action="{{ route ('galeries.store') }}">
             @csrf
             <div class="form-group">
                 <label for="image_url">Photo:</label>
                 <input type="text" class="form-control" name="image_url"/>
             </div>

             <div class="col-sm-12">

                    @if(session()->get('success'))
                      <div class="alert alert-success">
                        {{ session()->get('success') }}
                      </div>
                    @endif
                  </div>

             <div class="form-group">
                <label for="created_at">Ajouter a :</label>
                <input type="time" class="form-control" name="created_at"/>
            </div>
             <button type="submit" class="btn btn-primary">Ajouter une photo</button>
         </form>

     </div>
   </div>
   </div>
@endsection

resources/views/galeries/edit.blade.php
@extends('layouts.main')
@section('content')
<div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h1 class="display-3">Modifier une Photo</h1>
            <div>
                <a href='{{ route('galeries.index')}}' class="btn btn-primary">Retour</a>
            </div>

            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            <br />
            @endif
            <form method="post" action="{{ route('galeries.update',["galerie"=>$galerie->id])}}">
                @method('PATCH')
                @csrf
                <div class="form-group">

                    <label for="image_url">Photo:</label>
                    <input type="text" class="form-control" name="image_url" value={{ $galerie->image_url }} />
                </div>

                <div class="form-group">
                        <label for="created_at">Ajouter a :</label>
                        <input type="time" class="form-control" name="created_at"/>
                    </div>

                <button type="submit" class="btn btn-primary">Modifier</button>
            </form>
        </div>
    </div>
@endsection

resources/views/galeries/index.blade.php
@extends('layouts.main')
@section('content')
        <div class="col-sm-5">
          <h1 class="display-3">Galerie</h1>
          <div>
              <a href="{{ route('galeries.create')}}" class="btn btn-primary">Nouvelle Photo</a>
          </div>
          <div>
              <a href='{{ route('admin')}}' class="btn btn-primary">Retour à la page d'aministration</a>
          </div>
        </div>
              @foreach($galeries as $galerie)

                <div class="galerie_img">
                    <div class="card">

                        <div class="images_galerie">

                            <img class="card-img-top" src="{{$galerie->image_url}}" alt="Card image cap">
                        </div>

                        <div class="card-body">


                            <a href="{{ route('galeries.edit',["galerie"=>$galerie->id])}}" class="btn btn-primary">Modifier</a>

                            <form action="{{ route('galeries.destroy',["galerie"=>$galerie->id])}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger send" type="submit">Supprimer</button>
                                </form>

                        </div>
                    </div>
                </div>
               @endforeach


          <div class="col-sm-12">

                @if(session()->get('success'))
                  <div class="alert alert-success">
                    {{ session()->get('success') }}
                  </div>
                @endif
              </div>
@endsection